// Generates src/tools.generated.ts from the extracted OpenAI function definitions.
// Run: node scripts/gen-tools.mjs
// Source of truth: ~/workspace/x402/marketing/integrations/openai-functions.json
// (18 function definitions generated from the live OpenAPI specs).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const src = JSON.parse(
  readFileSync(
    "/home/hatch/workspace/x402/marketing/integrations/openai-functions.json",
    "utf8"
  )
);

function bodyKind(toolName, method, path) {
  if (method === "GET") return "query";
  if (toolName === "docextract_extract") return "multipart-file";
  return "json";
}

const tools = src.map((t) => {
  const fn = t.function;
  const meta = t._meta;
  const pathParams = [...meta.path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
  // docextract: accept base64 PDF content + optional filename; we build multipart.
  const properties = { ...fn.parameters.properties };
  if (t.function.name === "docextract_extract") {
    properties.file = {
      type: "string",
      description:
        "PDF document content, base64-encoded (will be sent as multipart field \"file\")",
    };
    properties.fileName = {
      type: "string",
      description: 'Original filename, e.g. "invoice.pdf" (default "upload.pdf")',
    };
  }
  const required = [...(fn.parameters.required || [])];
  // Normalize names: the extractor turned "/filing/{cik}/{accession}/sections"
  // into "filing___sections" — collapse runs of underscores.
  const name = fn.name.replace(/__+/g, "_");
  return {
    name,
    description: fn.description,
    service: meta.service,
    baseUrl: meta.base_url,
    method: meta.method,
    path: meta.path,
    price: meta.price_usdc,
    pathParams,
    bodyKind: bodyKind(fn.name, meta.method, meta.path),
    inputSchema: {
      type: "object",
      properties,
      required,
      additionalProperties: false,
    },
  };
});

const out = `// GENERATED by scripts/gen-tools.mjs — do not edit by hand.
// Source: openai-functions.json (18 definitions from the live OpenAPI specs).
import type { JsonSchema } from "./schema.js";
export interface McpToolDef {
  name: string;
  description: string;
  service: string;
  baseUrl: string;
  method: "GET" | "POST";
  path: string;
  price: string;
  pathParams: string[];
  /** how non-path params are sent: query string, JSON body, or multipart file upload */
  bodyKind: "query" | "json" | "multipart-file";
  inputSchema: {
    type: "object";
    properties: Record<string, JsonSchema>;
    required: string[];
    additionalProperties: false;
  };
}

export const TOOLS: McpToolDef[] = ${JSON.stringify(tools, null, 2)};
`;

writeFileSync(join(root, "src", "tools.generated.ts"), out);
console.log(`wrote src/tools.generated.ts with ${tools.length} tools`);
