// GENERATED by scripts/gen-tools.mjs — do not edit by hand.
// Source: openai-functions.json (18 definitions from the live OpenAPI specs).
import type { JsonSchema } from "./schema.js";
export interface McpToolDef {
  name: string;
  description: string;
  service: string;
  baseUrl: string;
  method: "GET" | "POST";
  path: string;
  price: string;
  pathParams: string[];
  /** how non-path params are sent: query string, JSON body, or multipart file upload */
  bodyKind: "query" | "json" | "multipart-file";
  inputSchema: {
    type: "object";
    properties: Record<string, JsonSchema>;
    required: string[];
    additionalProperties: false;
  };
}

export const TOOLS: McpToolDef[] = [
  {
    "name": "tenderwatch_search",
    "description": "[Government procurement search and fit-scoring] Search procurement opportunities Priced $0.02 USDC per call via x402 on Base.",
    "service": "tenderwatch",
    "baseUrl": "https://x402-tenderwatch.onrender.com",
    "method": "GET",
    "path": "/search",
    "price": "$0.02",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "q": {
          "type": "string",
          "description": "Keyword search (title/full-text)"
        },
        "source": {
          "type": "string",
          "description": "sam | ted | all (default all)",
          "enum": [
            "sam",
            "ted",
            "all"
          ]
        },
        "naics": {
          "type": "string",
          "description": "NAICS code filter (SAM)"
        },
        "psc": {
          "type": "string",
          "description": "PSC filter, e.g. D316 (SAM, client-side)"
        },
        "setAside": {
          "type": "string",
          "description": "Set-aside code filter, e.g. SBA (SAM)"
        },
        "postedFrom": {
          "type": "string",
          "description": "YYYY-MM-DD (default 30 days ago)"
        },
        "postedTo": {
          "type": "string",
          "description": "YYYY-MM-DD (default today)"
        },
        "limit": {
          "type": "integer",
          "description": "1–100 (default 20)"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "tenderwatch_opportunity_by_id",
    "description": "[Government procurement search and fit-scoring] Full detail for one opportunity Priced $0.01 USDC per call via x402 on Base.",
    "service": "tenderwatch",
    "baseUrl": "https://x402-tenderwatch.onrender.com",
    "method": "GET",
    "path": "/opportunity/{id}",
    "price": "$0.01",
    "pathParams": [
      "id"
    ],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "Path parameter for /opportunity/{id}"
        },
        "source": {
          "type": "string",
          "description": "sam | ted",
          "enum": [
            "sam",
            "ted"
          ]
        }
      },
      "required": [
        "id",
        "source"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "tenderwatch_fit_score",
    "description": "[Government procurement search and fit-scoring] Heuristic fit score 0–100 (no LLM) Priced $0.02 USDC per call via x402 on Base.",
    "service": "tenderwatch",
    "baseUrl": "https://x402-tenderwatch.onrender.com",
    "method": "POST",
    "path": "/fit-score",
    "price": "$0.02",
    "pathParams": [],
    "bodyKind": "json",
    "inputSchema": {
      "type": "object",
      "properties": {
        "capabilityStatement": {
          "type": "string",
          "description": "Vendor capability statement (≤20000 chars)"
        },
        "opportunity": {
          "type": "object",
          "description": "Normalized opportunity (title or description required)"
        }
      },
      "required": [
        "capabilityStatement",
        "opportunity"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "edgar-lens_search",
    "description": "[SEC EDGAR filing search and extraction] Full-text search of SEC EDGAR filings Priced $0.02 USDC per call via x402 on Base.",
    "service": "edgar-lens",
    "baseUrl": "https://x402-edgar-lens.onrender.com",
    "method": "GET",
    "path": "/search",
    "price": "$0.02",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "q": {
          "type": "string",
          "description": "Search phrase, e.g. 'revenue recognition'"
        },
        "forms": {
          "type": "string",
          "description": "Comma-separated filing forms"
        },
        "startDate": {
          "type": "string",
          "description": "YYYY-MM-DD"
        },
        "endDate": {
          "type": "string",
          "description": "YYYY-MM-DD"
        },
        "limit": {
          "type": "integer",
          "description": "limit"
        }
      },
      "required": [
        "q"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "edgar-lens_filing_sections",
    "description": "[SEC EDGAR filing search and extraction] Extract Item 1A and Item 7/2 sections from a filing Priced $0.03 USDC per call via x402 on Base.",
    "service": "edgar-lens",
    "baseUrl": "https://x402-edgar-lens.onrender.com",
    "method": "GET",
    "path": "/filing/{cik}/{accession}/sections",
    "price": "$0.03",
    "pathParams": [
      "cik",
      "accession"
    ],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cik": {
          "type": "string",
          "description": "Path parameter for /filing/{cik}/{accession}/sections"
        },
        "accession": {
          "type": "string",
          "description": "Path parameter for /filing/{cik}/{accession}/sections"
        },
        "sections": {
          "type": "string",
          "description": "Comma-separated: riskFactors, mda"
        }
      },
      "required": [
        "cik",
        "accession"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "edgar-lens_brief",
    "description": "[SEC EDGAR filing search and extraction] Extractive TF-IDF brief of a filing with section citations Priced $0.05 USDC per call via x402 on Base.",
    "service": "edgar-lens",
    "baseUrl": "https://x402-edgar-lens.onrender.com",
    "method": "GET",
    "path": "/brief/{cik}/{accession}",
    "price": "$0.05",
    "pathParams": [
      "cik",
      "accession"
    ],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cik": {
          "type": "string",
          "description": "Path parameter for /brief/{cik}/{accession}"
        },
        "accession": {
          "type": "string",
          "description": "Path parameter for /brief/{cik}/{accession}"
        },
        "sentences": {
          "type": "integer",
          "description": "Top sentences per section"
        }
      },
      "required": [
        "cik",
        "accession"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "trialscope_search",
    "description": "[Clinical trial search and change-deltas] Search clinical trials Priced $0.01 USDC per call via x402 on Base. Query ClinicalTrials.gov by keyword term, phase, overall status, lead sponsor, and location. Returns normalized study rows.",
    "service": "trialscope",
    "baseUrl": "https://x402-trialscope.onrender.com",
    "method": "GET",
    "path": "/search",
    "price": "$0.01",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "term": {
          "type": "string",
          "description": "Free-text search term (disease, drug, keyword)"
        },
        "phase": {
          "type": "string",
          "description": "Trial phase: 1, 2, 3, 4 (or PHASE1_PHASE2 style)"
        },
        "status": {
          "type": "string",
          "description": "Overall status, e.g. RECRUITING, COMPLETED"
        },
        "sponsor": {
          "type": "string",
          "description": "Lead sponsor name (partial match)"
        },
        "location": {
          "type": "string",
          "description": "Location text, e.g. Boston, MA"
        },
        "pageSize": {
          "type": "integer",
          "description": "Results per call (1-50, default 20)"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "trialscope_study",
    "description": "[Clinical trial search and change-deltas] Study dossier Priced $0.01 USDC per call via x402 on Base. Full normalized dossier for one study: conditions, interventions, eligibility summary, outcomes, locations, sponsor, dates.",
    "service": "trialscope",
    "baseUrl": "https://x402-trialscope.onrender.com",
    "method": "GET",
    "path": "/study/{nctId}",
    "price": "$0.01",
    "pathParams": [
      "nctId"
    ],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "nctId": {
          "type": "string",
          "description": "Path parameter for /study/{nctId}"
        }
      },
      "required": [
        "nctId"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "trialscope_snapshot",
    "description": "[Clinical trial search and change-deltas] Snapshot studies Priced $0.01 USDC per call via x402 on Base. Store current dossiers for up to 25 NCT ids. Returns { snapshotId, count, at }.",
    "service": "trialscope",
    "baseUrl": "https://x402-trialscope.onrender.com",
    "method": "POST",
    "path": "/snapshot",
    "price": "$0.01",
    "pathParams": [],
    "bodyKind": "json",
    "inputSchema": {
      "type": "object",
      "properties": {
        "nctIds": {
          "type": "array",
          "description": "nctIds"
        }
      },
      "required": [
        "nctIds"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "trialscope_delta",
    "description": "[Clinical trial search and change-deltas] Change-delta vs snapshot Priced $0.02 USDC per call via x402 on Base. Compare a stored snapshot record against the live study record. Returns { nctId, changed, changes: [{ field, before, after }] }.",
    "service": "trialscope",
    "baseUrl": "https://x402-trialscope.onrender.com",
    "method": "GET",
    "path": "/delta",
    "price": "$0.02",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "snapshotId": {
          "type": "string",
          "description": "Snapshot id from POST /snapshot"
        },
        "nctId": {
          "type": "string",
          "description": "NCT id that was in the snapshot"
        }
      },
      "required": [
        "snapshotId",
        "nctId"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "docextract_extract",
    "description": "[PDF to structured JSON extraction] Extract structured data from a PDF Priced up to $0.10 ($0.02 + $0.005/page) USDC per call via x402 on Base. Multipart upload, field name `file`. Limits: 10MB, 50 pages. x402 upto: authorizes $0.10 max, settles $0.02 + $0.005/page.",
    "service": "docextract",
    "baseUrl": "https://x402-docextract.onrender.com",
    "method": "POST",
    "path": "/extract",
    "price": "up to $0.10 ($0.02 + $0.005/page)",
    "pathParams": [],
    "bodyKind": "multipart-file",
    "inputSchema": {
      "type": "object",
      "properties": {
        "file": {
          "type": "string",
          "description": "PDF document content, base64-encoded (will be sent as multipart field \"file\")"
        },
        "fileName": {
          "type": "string",
          "description": "Original filename, e.g. \"invoice.pdf\" (default \"upload.pdf\")"
        }
      },
      "required": [
        "file"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "patentscope_search",
    "description": "[Patent search and prior-art ranking] Keyword patent search ($0.03) Priced $0.03 USDC per call via x402 on Base.",
    "service": "patentscope",
    "baseUrl": "https://x402-patentscope.onrender.com",
    "method": "GET",
    "path": "/search",
    "price": "$0.03",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "q": {
          "type": "string",
          "description": "Keyword query, e.g. 'wireless charging coil'"
        },
        "limit": {
          "type": "integer",
          "description": "limit"
        }
      },
      "required": [
        "q"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "patentscope_patent",
    "description": "[Patent search and prior-art ranking] Full patent record with claims ($0.02) Priced $0.02 USDC per call via x402 on Base.",
    "service": "patentscope",
    "baseUrl": "https://x402-patentscope.onrender.com",
    "method": "GET",
    "path": "/patent/{number}",
    "price": "$0.02",
    "pathParams": [
      "number"
    ],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "number": {
          "type": "string",
          "description": "Path parameter for /patent/{number}"
        }
      },
      "required": [
        "number"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "patentscope_prior_art",
    "description": "[Patent search and prior-art ranking] TF-IDF ranked prior-art search ($0.05) Priced $0.05 USDC per call via x402 on Base.",
    "service": "patentscope",
    "baseUrl": "https://x402-patentscope.onrender.com",
    "method": "POST",
    "path": "/prior-art",
    "price": "$0.05",
    "pathParams": [],
    "bodyKind": "json",
    "inputSchema": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "description": "Invention description to find prior art for"
        },
        "limit": {
          "type": "integer",
          "description": "limit"
        }
      },
      "required": [
        "description"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "alexandria_parts_search",
    "description": "[Automotive parts intelligence] Search Alexandria parts research Priced $0.03 USDC per call via x402 on Base.",
    "service": "alexandria",
    "baseUrl": "https://x402-alexandria.onrender.com",
    "method": "GET",
    "path": "/parts/search",
    "price": "$0.03",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "q": {
          "type": "string",
          "description": "Keywords, e.g. 'timing belt'"
        },
        "vehicle": {
          "type": "string",
          "description": "Badge/model/year hint, e.g. '93 metro xfi'"
        },
        "symptom": {
          "type": "string",
          "description": "Failure symptom phrasing, e.g. 'wind noise at speed'"
        },
        "limit": {
          "type": "integer",
          "description": "limit"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "alexandria_fitment_check",
    "description": "[Automotive parts intelligence] Fitment notes for a part × vehicle Priced $0.05 USDC per call via x402 on Base.",
    "service": "alexandria",
    "baseUrl": "https://x402-alexandria.onrender.com",
    "method": "GET",
    "path": "/fitment/check",
    "price": "$0.05",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "part": {
          "type": "string",
          "description": "Part description, e.g. 'door handle'"
        },
        "vehicle": {
          "type": "string",
          "description": "Badge/model/year, e.g. '94 swift'"
        },
        "limit": {
          "type": "integer",
          "description": "limit"
        }
      },
      "required": [
        "part"
      ],
      "additionalProperties": false
    }
  },
  {
    "name": "alexandria_failures",
    "description": "[Automotive parts intelligence] Common failure modes for a model Priced $0.02 USDC per call via x402 on Base.",
    "service": "alexandria",
    "baseUrl": "https://x402-alexandria.onrender.com",
    "method": "GET",
    "path": "/failures",
    "price": "$0.02",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "model": {
          "type": "string",
          "description": "Model hint, e.g. 'metro'. Omit for platform-wide."
        },
        "limit": {
          "type": "integer",
          "description": "limit"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  },
  {
    "name": "alexandria_demand",
    "description": "[Automotive parts intelligence] Demand signals across the dataset Priced $0.02 USDC per call via x402 on Base.",
    "service": "alexandria",
    "baseUrl": "https://x402-alexandria.onrender.com",
    "method": "GET",
    "path": "/demand",
    "price": "$0.02",
    "pathParams": [],
    "bodyKind": "query",
    "inputSchema": {
      "type": "object",
      "properties": {
        "limit": {
          "type": "integer",
          "description": "limit"
        }
      },
      "required": [],
      "additionalProperties": false
    }
  }
];
